### ISSUE TITLE
Confab generate overwrites files from other roles

### ISSUE THREAD

**Issue by narenst** [locationlabs/confab#2]
Running 

```
confab -R role1,role2 -e local generate
```

results in files only for _role2_ in the generated folder. Reversing the order of the roles results in only files for _role1_.

**Comment by jessemyers** [comment]
generate() is clearing the generated directory; we need to ensure that only runs once per invocation

Fabric has a @runs_once decorate; I believe it just caches the first function result, so it should work.

**Comment by jessemyers** [comment]
Fixed in:

https://github.com/locationlabs/confab/commit/ea2100783f5132f3b00a2a908ccde4da42b455d0
