### ISSUE TITLE
Confab converts empty string '' to None.

### ISSUE THREAD

**Issue by narenst** [locationlabs/confab#3]
In _data/default.py_ I have template parameter with value as empty string ''.

```
param1 = ''
```

Using this in the template as:

```
property1 = {{param1}}
```

When I run _generate_ it results in None as the value of for the property.

```
property1 = None
```

**Comment by jessemyers** [comment]
merge.py's _best() function is probably to blame

**Comment by jessemyers** [comment]
Should have been fixed by merge of pull request #4:

https://github.com/locationlabs/confab/commit/a47c10f12ae2653c040b725d2eddfd9656271c3d
